<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2018/8/20
 * Time: 10:20
 */

namespace app\admino\controller;


//卡片列表
use app\common\model\CheeseCardModel;
use app\common\model\SystemModel;
use app\common\model\UserModel;
use think\db\Query;

class CheeseCardShadowReview extends SingleTableBase
{
    protected $model = "cheese_card";
    protected $title = "影子发布卡片审核";

    protected $is_del = false;
    protected $is_edit = false;
    protected $is_add = false;

    protected $table_ext_button = [
        "通过" => "/Admino/CheeseCardShadowReview/inFavor",
        "不通过" => "/Admino/CheeseCardShadowReview/unFavor",
    ];
    protected $table_header = [
        "user_id" => "用户编号",
        "user_name" => "用户名",
        "full_pic_url" => "卡片",
        "tag" => "标签",
        "created_at" => "上传时间"
    ];
    protected $table_header_more = [
        "user_id" => "用户编号",
        "user_name" => "用户名",
        "full_pic_url" => "卡片",
        "tag" => "标签",
        "text" => "短语",
        "star" => "点赞数",
//        "is_delete" => "是否删除",
    ];
    protected $table_option = [
        "full_pic_url" => [
            'type' => self::TYPE_TX_COS,
            "host" => SystemModel::TX_COS_HOST,
            'path' => "user-card",
        ],
        "user_id" => [
            "table_width" => "100"
        ],
        "user_name" => [
            "table_width" => "100"
        ]
    ];

    protected $filter_header = ["tag"];

    protected function data(Query $model, $page, $search, $filter = false, $w = [])
    {
        return parent::data($model, $page, $search, $filter, ["review_status" => "NONE", "user_type" => "SHADOW"]); // TODO: Change the autogenerated stub
    }

    protected function dataIterator(&$data)
    {
        if (!empty($data["tag"])) {
            $data["tag"] = implode(",", json_decode($data["tag"]));
        }
    }


    public function delete($id)
    {
        CheeseCardModel::getInstance()->where(["id" => $id])->save([
            "is_delete" => 1
        ]);
        $this->displayBySuccess();
    }


    public function inFavor($id)
    {
        CheeseCardModel::getInstance()->where(["id" => $id])->save([
            "is_delete" => 0,
            "review_status" => "SUCCESS",
        ]);
        $this->displayBySuccess();
    }

    public function unFavor($id)
    {
        CheeseCardModel::getInstance()->where(["id" => $id])->save([
            "is_delete" => 1,
            "review_status" => 'FAIL',
        ]);
        $this->displayBySuccess();
    }
}