<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2018/8/20
 * Time: 10:20
 */

namespace app\admino\controller;


use app\common\model\SystemModel;
use app\common\model\UserModel;

class Feedback extends SingleTableBase
{
    protected $model = "feedback_user";
    protected $title = "普通用户卡片管理";

    protected $is_del = false;
    protected $is_add = false;
    protected $is_edit = false;
    protected $table_header = [
        "user_id" => "用户编号",
        "user_name" => "用户名",
        "feedback" => "内容",
        "user_concact" => "联系方式",
        "img_url" => "截图",
    ];
    protected $table_option = [
        "img_url" => [
            'type' => self::TYPE_TX_COS,
            "host" => SystemModel::TX_COS_HOST,
        ],
    ];

    protected $filter_header = ["feedback"];

    protected function dataIterator(&$data)
    {
        $data["user_name"] = UserModel::getInstance()->where(["id"=>$data["user_id"]])->find()["nickName"];
        parent::dataIterator($data); // TODO: Change the autogenerated stub
    }
}