<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/9/4
 * Time: 11:50
 */

namespace app\admino\controller;

use app\common\controller\BaseController;
use app\common\model\ProductModel;
use app\common\model\UserModel;
use think\db\Query;
use think\Request;

class Order extends SingleTableBase
{

    protected $model = "order";

    protected $is_del = false;
    protected $is_add = false;
    protected $is_edit = false;


    protected $table_header = [
        'order_number' => "订单编号",
        'user_id' => "用户编号",
        'nickName' => "用户昵称",
        'user_phone' => "联系电话",
        'buy_name' => "商品名",
        'product_id' => "产品编号",
        'cost_exchange' => "消耗cheese卡",
        'created_at' => "创建时间",
    ];

    protected $table_header_more = [

    ];

    protected $filter_header = [
        "order_number",
        "user_id",
    ];

    protected function data(Query $model, $page, $search, $filter = false, $w = [])
    {
        return parent::data($model, $page, $search, $filter, $w); // TODO: Change the autogenerated stub
    }

    protected function dataIterator(&$data)
    {
        $data += UserModel::getInstance()->field(["nickName"])->where(["id" => $data["user_id"]])->find();
    }

}