<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2018/8/21
 * Time: 14:52
 */

namespace app\admino\controller;


use app\common\model\CheeseCardModel;
use app\common\model\PickGroupModel;
use app\common\model\SystemModel;
use think\db\Query;

class PickGroupComment extends SingleTableBase
{
    protected $model = "pick_group_comment";
    protected $primary_show = false;
    protected $title = "pick评论";

    protected $is_add = false;
    protected $is_edit = false;

    protected $table_header = [
//        "user_id" => '用户编号',
        "left_cheese_card" => '左图',
        "right_cheese_card" => '右图',
//        "pick_group_id" => 'pick组id',
        "content" => '评论内容'
    ];
    protected $table_header_more = [
//        "user_id" => '用户编号',
        "left_cheese_card" => '左图',
        "right_cheese_card" => '右图',
//        "pick_group_id" => 'pick组id',
        "content" => '评论内容'
    ];

    protected $table_option = [

        "left_cheese_card" => [
            'type' => self::TYPE_TX_COS,
            "host" => SystemModel::TX_COS_HOST,
            'path' => "user-card",
        ],
        "right_cheese_card" => [
            'type' => self::TYPE_TX_COS,
            "host" => SystemModel::TX_COS_HOST,
            'path' => "user-card",
        ],
    ];

    protected function dataIterator(&$data)
    {
        $pk = PickGroupModel::getInstance()->where(["id" => $data["pick_group_id"]])->getAssembly();
        $data["left_cheese_card"] = $pk["left_cheese_card"]["full_pic_url"];
        $data["right_cheese_card"] = $pk["right_cheese_card"]["full_pic_url"];
        parent::dataIterator($data); // TODO: Change the autogenerated stub
    }


    protected function data(Query $model, $page, $search, $filter = false, $w = [])
    {
        if ($_GET["id"]) {
            $w = [
                "pick_group_id" => $_GET["id"]
            ];
        }
        return parent::data($model, $page, $search, $filter, $w); // TODO: Change the autogenerated stub
    }


}