<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/9/4
 * Time: 11:50
 */

namespace app\admino\controller;

use app\common\controller\BaseController;
use app\common\model\ProductModel;
use app\common\model\SystemModel;
use think\Request;

class Product extends SingleTableBase
{

    protected $model = "product";
    protected $title = "产品列表";

    protected $is_del = false;

    protected $table_ext_button = [
        "上架" => "/Admino/Product/shelf",
        "下架" => "/Admino/Product/obtained",
        "修改库存" => "/Admino/Product/saveStock",
    ];

    protected $table_header = [
        'id' => "产品编号",
        'name' => "产品名称",
        'stock' => '库存',
        'number' => '消耗cheese卡数',
        'price' => '原价',
        'status' => '状态',
    ];

    protected $table_header_more = [
        'name' => "产品名称",
        'img_src' => '封面图',
        'introduce' => '产品详情图片',
//        'stock' => '库存',
        'number' => '消耗cheese卡数',
        'price' => '原价',
        'status' => '状态',
    ];

    protected $filter_header = [
        "name",
    ];
    protected $table_option = [
        "img_src" => [
            "type" => self::TYPE_TX_COS,
            "host" => SystemModel::TX_COS_HOST,
            "path" => "product",
        ],
        "introduce" => [
            "type" => self::TYPE_TX_COS,
            "host" => SystemModel::TX_COS_HOST,
            "path" => "product",
        ],
        "status" => [
            "type" => self::TYPE_SELECT,//或者TYPE_MULTIPLE_SELECT
            "table_width" => "300",
            "data" => [0 => "下架", 1 => "上架",]

        ],
        "id" => [
            "type" => self::TYPE_NUM,
            "table_width" => "100",

        ],
        "stock" => [
            "type" => self::TYPE_NUM,
        ],
        "number" => [
            "type" => self::TYPE_NUM,
            "table_width" => "300",
        ],
    ];

    public function saveStock($id)
    {
        $this->table_header_more = [
            'name' => "产品名称",
            "stock" => "库存"
        ];
        parent::save($id); // TODO: Change the autogenerated stub
    }


    public function shelf($id)
    {
        ProductModel::getInstance()->where(["id" => $id])->save(["status" => 1]);
        $this->displayBySuccess();
    }

    public function obtained($id)
    {

        ProductModel::getInstance()->where(["id" => $id])->save(["status" => 0]);
        $this->displayBySuccess();
    }
}