<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2018/8/20
 * Time: 10:20
 */

namespace app\admino\controller;


use app\common\model\ReportModel;
use app\common\model\SystemModel;
use app\common\model\UserModel;
use think\db\Query;

class ReportUser extends SingleTableBase
{
    protected $model = "report";
    protected $title = "用户举报管理";

//    protected $is_del = false;
    protected $is_add = false;
    protected $is_edit = false;
    protected $table_header = [
        "user_id" => "用户编号",
        "user_name" => "举报人昵称",
//        "report_user_id" => "被举报的用户id",
        "user_report_content" => "举报内容",
    ];

    protected $filter_header = ["user_name"];

    protected $table_ext_button_iframe = [
        "被举报的用户信息" => "/Admino/ReportUser/user",
    ];

    public function user($id)
    {
        $data = ReportModel::getInstance()->where(["id" => $id])->find();
        SystemModel::redirect("/Admino/UserExt/save", [
            "id" => $data["user_id"],
//            "is_only_read" => 1,
        ]);
    }

    protected function data(Query $model, $page, $search, $filter = false, $w = [])
    {
        return parent::data($model, $page, $search, $filter, [
            "report_type" => "USER",
            "is_examine" => "0",
        ]); // TODO: Change the autogenerated stub
    }

    protected function dataIterator(&$data)
    {
        $data["user_name"] = UserModel::getInstance()->where(["id" => $data["user_id"]])->find()["nickName"];
        parent::dataIterator($data); // TODO: Change the autogenerated stub
    }
}