<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2018/8/20
 * Time: 10:20
 */

namespace app\admino\controller;


use app\common\model\CheeseCardModel;
use app\common\model\ReportModel;
use app\common\model\SystemModel;
use app\common\model\UserModel;
use think\db\Query;

class ReportCard extends SingleTableBase
{
    protected $model = "report";
    protected $title = "卡片举报管理";

//    protected $is_del = false;
    protected $is_add = false;
    protected $is_edit = false;
    protected $table_header = [
        "user_id" => "用户编号",
        "user_name" => "举报人昵称",
//        "cheese_card_id" => "被举报的卡片id",
        "full_pic_url" => "卡片",
        "cheese_card_report_content" => "举报卡片内容",
    ];

    protected $filter_header = ["user_name"];

    protected $table_ext_button = [
        "删除卡片" => "/Admino/ReportCard/deleteCheeseCard",
        "忽略" => "/Admino/ReportCard/ignore",
    ];

    protected $table_option = [

        "full_pic_url" => [
            'type' => self::TYPE_TX_COS,
            "host" => SystemModel::TX_COS_HOST,
            'path' => "user-card",
        ],
    ];


    public function ignore($id)
    {
        ReportModel::getInstance()->where(["id" => $id])->save([
            "is_examine" => 1
        ]);
        $this->displayBySuccess();
    }

    public function deleteCheeseCard($id)
    {
        $data = ReportModel::getInstance()->where(["id" => $id])->find();
        $cheese_card_id = $data["cheese_card_id"];
        CheeseCardModel::getInstance()->where(["id" => $cheese_card_id])->save([
            "is_delete" => 1
        ]);
        ReportModel::getInstance()->where(["id" => $id])->save([
            "is_examine" => 1
        ]);
        $this->displayBySuccess();
    }


    protected function data(Query $model, $page, $search, $filter = false, $w = [])
    {
        return parent::data($model, $page, $search, $filter, [
            "report_type" => "CHEESECARD",
            "is_examine" => "0",
        ]); // TODO: Change the autogenerated stub
    }

    protected function dataIterator(&$data)
    {

        $data["full_pic_url"] = CheeseCardModel::getInstance()->where(["id" => $data["cheese_card_id"]])->find()["full_pic_url"];

        $data["user_name"] = UserModel::getInstance()->where(["id" => $data["user_id"]])->find()["nickName"];
        parent::dataIterator($data); // TODO: Change the autogenerated stub
    }
}