<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2018/5/25
 * Time: 9:16
 */

namespace app\admino\controller;


use app\common\model\SystemModel;
use app\common\model\UserModel;
use app\common\model\UserShadowGroupModel;
use app\common\model\WechatModel;
use EasyWeChat\Foundation\Application;
use Guzzle\Stream\Stream;
use think\db\Query;

class UserShadow extends SingleTableBase
{
    protected $model = "user";
    protected $primary_show = false;
    protected $title = "用户列表";
//    protected $is_add = false;
    protected $is_del = false;

    protected $index_view = "/usershadow/index";
    protected $table_header = [
        "username" => "登录名",
        "nickName" => "姓名",
        "phone" => "手机",
        "gender" => '性别',
//        "type" => "账号类型",
        "group" => "分组",
//        "cheese_num" => 'cheese卡数',
//        "created_at" => '注册时间',
        "is_black" => '状态',
    ];
    protected $table_header_more = [
        "nickName" => "用户姓名",
        "avatarUrl" => "用户头像",
        "phone" => "手机",
        "gender" => '性别',
        "age" => '用户年龄',
        "city" => "用户所在城市",
        "province" => "用户所在省份",
        "country" => "用户所在国家",
        "constellation" => "星座",
        "cheese_num" => 'cheese卡数',
        "signature" => '个性签名',
        "is_black" => '是否拉黑',
        "group" => "分组"
    ];

    protected $table_ext_button = [
        "发布卡片" => "/Admino/UserShadow/cheeseCardShadowByUser"

    ];


    public function cheeseCardShadowByUser($id)
    {
        SystemModel::redirect("/Admino/CheeseCardShadowByUser/save?user_id={$id}");
    }

    protected $filter_header = [
        "nickName",
        "gender",
        "phone",
        "group",
    ];


    protected $table_option = [
        "avatarUrl" => [
            "type" => self::TYPE_TX_COS,
            "host" => SystemModel::TX_COS_HOST,
            "path" => "user-picture",
        ],
        "phone" => [
            "table_width" => "300",
        ],
        "type" => [
            "type" => self::TYPE_SELECT,//或者TYPE_MULTIPLE_SELECT
            "table_width" => "300",
            "data" => [
                "SHADOW" => "影子账户",
                "NONE" => "普通账户",
            ]
        ],
        "gender" => [
            "type" => self::TYPE_SELECT,//或者TYPE_MULTIPLE_SELECT
            "table_width" => "300",
            "data" => [
                1 => "男", 2 => "女",
            ]

        ],
        "group" => [
            "type" => self::TYPE_SELECT,//或者TYPE_MULTIPLE_SELECT
            "table_width" => "300",
            "data" => [
                "NONE" => "无",
            ]
        ],
        "is_black" => [
            "type" => self::TYPE_SELECT,//或者TYPE_MULTIPLE_SELECT
            "table_width" => "300",
            "data" => ["0" => "正常", "1" => "禁用",]
        ],
        "cheese_num" => [
            "type" => self::TYPE_DISABLED_TEXT,//或者TYPE_MULTIPLE_SELECT
            "table_width" => "300"
        ],
        "password" => [
            "type" => self::TYPE_CLEAR_TEXT_PASSWORD,//或者TYPE_MULTIPLE_SELECT
            "table_width" => "300"
        ],
    ];

    protected function _initialize()
    {
        $data = UserShadowGroupModel::getInstance()->select();
        $result = ["NONE" => "无分组"];
        for ($i = 0; $i < count($data); $i++) {
            $result[$data[$i]["name"]] = $data[$i]["name"];
        }
        $this->table_option["group"]["data"] = $result;
        parent::_initialize();
    }

    protected function data(Query $model, $page, $search, $filter = false, $w = [])
    {
        return parent::data($model, $page, $search, $filter, ["type" => "SHADOW"]); // TODO: Change the autogenerated stub
    }

    public function appCode()
    {
        $data = WechatModel::getWxaCodeUnLimit("pages/mine/mine", "test");
        exit(($data));
    }


    public function changePassword($user_id, $password)
    {
        UserModel::getInstance()->where([
            "id" => $user_id,
        ])->save([
            "password" => $password,
        ]);
    }


    public function selectUser($page = 1, $search = false, $filter = false)
    {
        $this->title = "选择影子账户";//
        $this->index_view = "/user_shadow_ext/select";
        parent::index($page, $search, $filter);
    }

    public function save($id = 0)
    {
        if ($id == 0) {
            $this->table_header_more = [
                "username" => "登录名",
                "password" => "密码",
                "nickName" => "姓名",
                "avatarUrl" => "用户头像",
                "phone" => "手机",
                "gender" => '性别',
                "signature" => '个性签名',
                "group" => "分组"
            ];
        }
        parent::save($id); // TODO: Change the autogenerated stub
    }
}