<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2018/5/25
 * Time: 9:16
 */

namespace app\admino\controller;


use app\common\model\BillModel;
use app\common\model\SystemModel;
use app\common\model\UserModel;
use think\db\Query;

class UserExt extends SingleTableBase
{
    protected $model = "user";
    protected $primary_show = false;
    protected $title = "用户列表";
    protected $is_add = false;
    protected $is_del = false;

    protected $save_view = "/userext/save";
    protected $index_view = "/userext/index";
    protected $table_header = [
        "nickName" => "姓名",
//        "avatarUrl" => "用户头像",
        "gender" => '性别',
        "cheese_num" => 'cheese卡数',
        "created_at" => '注册时间',
        "signature" => '个性签名',
        "is_black" => '状态',
    ];
    protected $table_header_more = [
        "nickName" => "用户姓名",
        "avatarUrl" => "用户头像",
        "gender" => '性别',
        "age" => '用户年龄',
//        "city" => "用户所在城市",
//        "province" => "用户所在省份",
//        "country" => "用户所在国家",
//        "constellation" => "星座",
        "cheese_num" => 'cheese卡数',
        "signature" => '个性签名',
        "is_black" => '是否拉黑',
    ];

    protected $filter_header = [
        "nickName",
        "gender",
    ];

//    protected $table_ext_button = [
//        "cheese卡使用明细" => "/Admino/UserExt/order"
//    ];

    protected $table_option = [
        "avatarUrl" => [
            "type" => self::TYPE_TX_COS,
            "host" => SystemModel::TX_COS_HOST,
            "path" => "user-picture",
        ],
        "gender" => [
            "type" => self::TYPE_SELECT,//或者TYPE_MULTIPLE_SELECT
            "table_width" => "300",
            "data" => [
                1 => "男", 2 => "女",]

        ],
        "is_black" => [
            "type" => self::TYPE_SELECT,//或者TYPE_MULTIPLE_SELECT
            "table_width" => "300",
            "data" => [0 => "正常", 1 => "禁用",]
        ],
        "cheese_num" => [
            "type" => self::TYPE_DISABLED_TEXT,//或者TYPE_MULTIPLE_SELECT
            "table_width" => "300"
        ],
    ];

    public function order($id)
    {
        SystemModel::redirect("/Admino/Order/index.html", [
            "filter" => ["user_id" => $id]
        ]);
    }

    /**
     *【操作】添加影子账户
     * @method /Admino/User/addShadow.json
     * @return void
     */
    public function addShadow()
    {
        $_POST["openid"] = time() . rand(0, 10000);
        if (empty($_POST["password"]) || empty($_POST["username"])) {
            $this->displayByError("账号密码不可为空");
        }
        UserModel::getInstance()->add($_POST);
        $this->displayBySuccess();
    }


    protected function data(Query $model, $page, $search, $filter = false)
    {
        $model->where(["type" => "NONE"]);
        return parent::data($model, $page, $search, $filter); // TODO: Change the autogenerated stub
    }


    public function cheeseDetail($id)
    {
        $data = BillModel::getInstance()->where(["user_id"=>$id])->order(["created_at desc"])->select();
        $this->displayByData($data);
    }

}